config/routes.rb
Redidea::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  match '/activities/my_index', :to => 'activities#my_index'
  resources :activities

  resources :advises, :only => [:index, :create, :update]

  devise_for :users do
    match "/users/sign_up" => redirect("/users/sign_in")
  end

  resources :comments
  root :to => "myspaces#show"
  resources :ideas
  match '/admin', :to => 'admins#admin'
  match '/invite', :to => 'admins#invite'
  match '/likes', :to => 'likes#create'
  resources :plans, :only => [:index, :create, :update]
  match '/static/an2012', :to => 'static#an2012'
  resources :messages
  match '/myspace', :to => 'myspaces#show'

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer(4)      not null, primary key
#  content    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

# -*- encoding : utf-8 -*-
class Message < ActiveRecord::Base
  attr_accessible :content
  validates :content, :presence => true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
  end

  def create
    @message = Message.create!(params[:message])
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if @message.update_attributes(params[:message])
      redirect_to @message, :notice  => "Successfully updated message."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_url, :notice => "Successfully destroyed message."
  end
end

app/views/messages/_form.html.erb
<%= form_for @message, :remote => true  do |f| %>
  <p>
    <%= f.text_area :content, :style => "width:255px;", :rows => 4 %>
  </p>
  <div id="message_input_button">
    <input type="image" src="http://a.xnimg.cn/n/core/res/webpager/send-button.png">
  </div>
<% end %>

app/views/messages/_message.html.erb
<li>
  <span class="created_at"><%= message.created_at.strftime("%H:%M") %></span>
  <%= message.content %>
</li>

app/views/messages/create.js.erb
<% broadcast "/messages/new" do  %>
$("#chat").append("<%= escape_javascript render(@message) %>");
var __list = $('.message_list');
var __chat = $('#chat');
__list.scrollTop( __chat.height() );
<% end %>
$("#new_message")[0].reset();

app/views/messages/index.html.erb
<%= "Messages" %>

<table>
  <tr>
    <th>Content</th>
  </tr>
  <% for message in @messages %>
    <tr>
      <td><%= message.content %></td>
      <td><%= link_to "Show", message %></td>
      <td><%= link_to "Edit", edit_message_path(message) %></td>
      <td><%= link_to "Destroy", message, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Message", new_message_path %></p>

app/views/messages/new.html.erb
<%= "Chat" %>
<!--
<div class="message_box" >
  <div class="message_list">
    <dl id="chat">
      <%= render @messages %>
    </dl>
  </div>
  <div class="input">
    <%= render 'messages/form' %>
  </div>
</div>

<div id="friend">
<button class='button' type='submit'>
  <%= image_tag "web-app-theme/icons/tick.png"%>聊天
</button>
</div>

-->