config/routes.rb
Redidea::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  match '/activities/my_index', :to => 'activities#my_index'
  resources :activities

  resources :advises, :only => [:index, :create, :update]

  devise_for :users do
    match "/users/sign_up" => redirect("/users/sign_in")
  end

  resources :comments
  root :to => "myspaces#show"
  resources :ideas
  match '/admin', :to => 'admins#admin'
  match '/invite', :to => 'admins#invite'
  match '/likes', :to => 'likes#create'
  resources :plans, :only => [:index, :create, :update]
  match '/static/an2012', :to => 'static#an2012'
  resources :messages
  match '/myspace', :to => 'myspaces#show'

end

app/models/idea.rb
# == Schema Information
#
# Table name: ideas
#
#  id          :integer(4)      not null, primary key
#  user_id     :integer(4)
#  title       :string(255)
#  content     :text
#  created_at  :datetime
#  updated_at  :datetime
#  activity_id :integer(4)      default(1)
#

class Idea < ActiveRecord::Base
  acts_as_commentable
  
  validates :content, :presence     => true,
                      :length       => { :maximum => 400 }
  validates :title,   :presence     => true,
                      :length       => { :maximum => 30 }
  validates :user_id, :presence => true

  belongs_to :user 
  belongs_to :activity
  attr_accessible :title, :created_at, :content, :activity_id

  has_many :likes, :dependent => :destroy
  has_many :liked_by, :through => :likes, :source => :user

  def liked_by?(user)
    likes.find_by_user_id(user)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorized_user, :only => :destroy


  # GET /ideas
  # GET /ideas.json
  def index
    @idea = Idea.new
    @ideas = Array.new
    @liked_ideas = Array.new
    @plans = current_user.plans

    @scope = params[:scope] || 'liked'
    @scopes = [:liked, :mine, :upload, :rule]

    if @scope == "mine" 
      @ideas = current_user.ideas
      @ideas.reverse!
    elsif @scope == "liked" 
      @liked_ideas = current_user.liking
      @ideas = Idea.all - @liked_ideas - current_user.ideas
      @liked_ideas.reverse!
    elsif @scope == "upload"
      @plan = Plan.find(:first, :conditions => "user_id = #{current_user.id}")
      if not @plan
        @plan = Plan.new
      end 
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea  = current_user.ideas.build(params[:idea])
    mypath = ideas_path + "?scope=mine"

    respond_to do |format|
      if @idea.save
        @scope = 'mine'
        @ideas = current_user.ideas
        @ideas.reverse!

        format.html { redirect_to mypath, :notice => t(:idea_successfully_created) }
        format.json { render :json => @idea, :status => :created, :location => @idea }
        format.js 
      else
        format.html { redirect_to mypath, :notice => t(:idea_was_unsuccessfully_created) }
        format.json { render :json => @idea.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    mypath= ideas_path + "?scope=mine"

    respond_to do |format|
      format.html { redirect_to mypath }
      format.json { head :ok }
      format.js
    end
  end

  private
    def authorized_user
      @idea = current_user.ideas.find_by_id(params[:id])
      redirect_to root_path if @idea.nil?
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%# encoding: utf-8 %>
<%= form_for(@idea, :remote => true) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :style => "width: 95%;" %>
  </div>
  <div class="field">
    <div class="idea_content">
      <div style="display: none;" node-type="num" class="num">
        请文明发言，还可以输入<span>400</span>字
      </div>
      <div class="title"><%= f.label :content %></div>
      <%= f.text_area :content, :style => "width: 95%;", :rows => 6 %>
    </div>
  </div>
  <button class='button' type='submit'>
    <%= image_tag "web-app-theme/icons/tick.png"%>发布
  </button>
  <p></p>
  <p></p>
<% end %>

app/views/ideas/_idea_box.html.erb
<%# encoding: utf-8 %>


<% if @scope == 'mine' %>
  <%= render 'ideas/form' %>
<% else %>
  <div class="update-notice">
    <%= "没有新鲜点子啦。" if @ideas.empty? %>
  </div>
<% end %>

<div class="inner">
  <ul id="myideas" class="list" style="word-break:break-all;">
    <!-- unlied ideas -->
    <% if @scope != 'mine' and not @ideas.empty? %>
      <li><%= "还有#{@ideas.count}个待评点子。"  %></li>
    <% end %>

    <% @ideas.each do |idea| %>
      <%= render :partial => "ideas/my_ideas", :locals => { :idea => idea } %>
    <% end %>

    <!-- liked ideas -->
    <% if @scope == 'liked' and not @liked_ideas.empty? %>
    <li>已评价点子：</li>

    <% @liked_ideas.each do |idea| %>
    <li class='ideaid<%= idea.id%>'>
      <div class="left">
        <%= image_tag("/images/icons/#{idea.user_id % 67}.png") %>
				<div class ="user_icon">
					<span class="id<%= idea.user_id %>">
						<% num_of_ideas = User.find(:first, :conditions => "id = #{idea.user_id}").ideas.length %>
						<b>已发点子数:<%= num_of_ideas %></b>
						<b></b>
					</span>
      	</div>
			</div>
      <div class='item'>
        <b><%= idea.title %></b>
        <p><%= (idea.content).html_safe %></p>
        <div class='right small'>
          <% my_like = current_user.likes.find_by_idea_id(idea.id) %>
          <% score = my_like.score %>
          <% scores = ['不喜欢','没感觉','还不错','牛'] %>
          <i class='vline'>我觉得<%= scores[score] %></i>
          <i class='vline'>|</i>
          <%= link_to "评论(#{idea.comments.count})", comments_path(:idea_id => idea.id), { :remote => true, :class => "comment_link" } %>
        </div>
        <div class='small'><%= time_ago_in_words(idea.created_at) %>前</div>
	<div class="id<%= idea.id %> comments"> 
	</div>
      </div>
    </li>
    <% end %>
    <% end %>
  </ul>
</div>

app/views/ideas/_rule.html.erb
<%# encoding: utf-8 %>
<h2>欢迎参加红点子大奖赛</h2>
<p>很多同事都知道前一段时间收集新想法的头脑风暴活动，这个活动中我们想出了很多好的创新点子，为了鼓励大家想出更好的商业创意,公司现举办一个大奖赛，也拿出了很诱人的奖品，希望大家积极参与，提出更好的商业计划或者商业创意，赢取奖品。</p>

<h4>最佳商业计划奖：</h4>
<p><b>奖项设置:</b>一等奖一名,奖品为iPad一台; 二等奖二名,奖品为1TB USB3.0移动硬盘一个。</p>
<p><b>参赛办法:</b>请完成一份商业策划书，格式参考<%= link_to '商业策划书模板', "/plan_template.doc", :class => 'small-button' %>。在<%= link_to '"提交策划书"', "#{ideas_path}?scope=upload" %>页面提交即可。（提示：模板中红色部分内容会作为评审重点，请格外关注）。</p>
<p><b>评奖办法：</b>本奖项由产品市场部特邀公司内部资深人士组成的评审委员会评审产生。 即刻行动起来吧，这轻轻的一笔或许能成就你非凡的未来！</p>

<h4>最佳商业创意奖：</h4>
<p><b>奖项设置:</b>一等奖一名,iPod touch4 一台；二等奖二名,奖品为1TB USB3.0移动硬盘一个</p>
<p><b>参赛办法:</b>在<%= link_to '"提交点子"', "#{ideas_path}?scope=mine" %>页面提交你的创意点子，请尽量用简短的语言把你的想法描述清楚，以便争取更好的评价。（提示：用文字抓住读者的心是一门学问，通过简短的描述让表达更清晰是一种技巧，我想你懂的~~）。</p>
<p><b>评奖办法：</b>每个点子都会接受公司全体同事的评价，评价最好的点子将入围前10名，然后大家会对前10名再次进行10分制投票，得分最高的获得最终的“最佳商业创意奖”。现在就去支持你喜欢的<%= link_to '创意点子', "#{ideas_path}?scope=liked" %>吧。</p>

<h4>截止日期</h4>
<p>两个奖项的截止时间均为2012年2月15日零点,过时将无法提交点子和策划书。</p>

<h4>评审时间</h4> 
<p> 2012年2月20日前完成评选</p>
<h4>注意事项</h4> 
<div class="content">
  <ul>
    <li>时值年底，很多同事手头的工作都进入了冲刺阶段，所以为了公平起见，请不要利用工作时间来完成本次参赛所需准备的作业。</li>
    <li>允许自行结合成课题组参加比赛，课题组的点子或者策划书请以组长个人身份在网站提交，提交时注明小组参赛即可</li>
  </ul>
</div>
<h2>祝你成功！</h2>
<p>2011年12月21日</p>

app/views/ideas/_unlike.html.erb
<%= link_to 'upload plan', plans_path %>
<br>

  <div class="content">
    <% if @scope == :mine %>
    <h1>My ideas</h1>
    <%= render 'form' %>
    <% else %> 
    <h1>Listing ideas</h1>
    <% end %>
  </div>

  <% @ideas.each do |idea| %>
  <div class="content">
    <div class="inner">
      <p class="first">
        <%= image_tag("/images/icons/#{idea.user_id % 60}.png") %> <%= idea.title %>
      </p>
      <hr />
      <p>
        <%= idea.content %>
      </p>
      <hr />

      <div class="right">
        <% if @scope == :mine %>
        <%= link_to 'Destroy', idea, :confirm => 'Are you sure?', :method => :delete %>
        <% else %> 
        <%= link_to 'tread', likes_path, :method => :post %>
        <%= link_to 'like', likes_path, :method => :post %>
        <%= link_to 'surprise', likes_path, :method => :post %>
        <%= link_to 'soy', likes_path(:idea_id => idea.id, :score => -1), :method => :get %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

app/views/ideas/destroy.js.erb
<% broadcast "/ideas/destroy" do  %>
  {
    "user_email": "<%= current_user.email %>",
    "user_id": "<%= current_user.id %>",
    "action"   : "delete"
  }
<% end %>

<% if @idea.valid? %>
    $('#myideas').find('.ideaid<%= @idea.id%> ').fadeOut(1000,function(){
      $(this).remove();
    } );

  flashController.doSuccess('<p>删除成功</p>');
<% end %>

app/views/ideas/index.html.erb
<%# encoding: utf-8 %>

<div class="block" id="block-text">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <% @scopes.each do |s| %>
      <li <%= "class='active first'" if s.to_s == @scope %> ><%= link_to t(s), "#{ideas_path}?scope=#{s}", :remote => true %></li>
      <% end %>
    </ul>
  </div>

  <div class="content">
    <% if @scope == 'rule' or @scope == 'upload' %>
    <%= render @scope %>
    <% else %>
    <%= render 'idea_box' %>
    <% end %>
  </div>
</div>

app/views/ideas/index.js.erb
<%# encoding: utf-8 %>

(function() {
  var scope_pat = new RegExp("scope=(<%= j @scope %>)", 'g');

  <% if @scope == 'rule' or @scope == 'upload' %>
    var $active = $('.secondary-navigation .wat-cf li.active');
    if ($active.length) {
      var ret = scope_pat.exec( $active.find('a').attr('href') );
      if (ret && ret[1] === "<%= @scope %>") {
        return;
      } 
    }
    $('#main .block .content').html( "<%= j render @scope %>" );

  <% else %>
      $('#main .block .content').html( " <%= j render 'idea_box' %> " );
  <% end %>

  $('.secondary-navigation .wat-cf li').find('a').each( function(idx, el) {
    var ret = scope_pat.exec( $(el).attr('href') );
    if ( ret && ret[1] ) {
      $(el).parent().addClass('active first');
    } else {
      $(el).parent().removeClass('active first');
    }
  } );

})();