config/routes.rb
Redidea::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  match '/activities/my_index', :to => 'activities#my_index'
  resources :activities

  resources :advises, :only => [:index, :create, :update]

  devise_for :users do
    match "/users/sign_up" => redirect("/users/sign_in")
  end

  resources :comments
  root :to => "myspaces#show"
  resources :ideas
  match '/admin', :to => 'admins#admin'
  match '/invite', :to => 'admins#invite'
  match '/likes', :to => 'likes#create'
  resources :plans, :only => [:index, :create, :update]
  match '/static/an2012', :to => 'static#an2012'
  resources :messages
  match '/myspace', :to => 'myspaces#show'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer(4)      not null, primary key
#  title            :string(50)      default("")
#  comment          :text
#  commentable_id   :integer(4)
#  commentable_type :string(255)
#  user_id          :integer(4)
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorized_user, :only => :destroy
  
  # GET /comments
  # GET /comments.json
  def index
    @idea = Idea.find(params[:idea_id])
    @comment = Comment.new(:commentable_id => @idea.id)
    @comments = @idea.comments
    respond_to do |format|
      format.js 
      format.json { render json: @comments }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @idea = Idea.find(params[:comment][:commentable_id])
    @comment = @idea.comments.create(:comment => params[:comment][:comment])
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        @comments = @idea.comments
        @comment = Comment.new(:commentable_id => @idea.id)
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
        format.js { render "index" }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js { redirect_to ideas_path+"?scope=liked" }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @idea = @comment.commentable
    @comment.destroy
    @comments = @idea.comments
    @comment = Comment.new(:commentable_id => @idea.id)

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.js { render "index" }
    end
  end

  private
    def authorized_user
      comment = Comment.find(params[:id])
      redirect_to root_path if comment.user != current_user
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_box.js.erb
<%# encoding: utf-8 %>

<ul class='comment'>
  <% @comments.each do |comment| %>
    <li class='comid<%= comment.id %>'>
			<div class='left'>
      	<%= image_tag("/images/icons/#{comment.user_id % 67}.png") %>
			</div>
      <%= comment.comment %>
			<div class='right'>
			<% if(comment.user_id==current_user.id) %>
				<%= link_to 'x', comment, :confirm => '你确认删除？', :method => :delete, :class => 'small-button', :remote => true %>
			<%end%>
			</div>
    </li>
  <% end %>
</ul>

<%= render 'form' %>

app/views/comments/_form.html.erb
<%= form_for(@comment, :remote => true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :comment %>
  <%= f.hidden_field :commentable_id %>
  <%= f.submit "评论", :style => "height: 24px; width: auto; margin-left: 10px; margin-top: 0px; padding-left: 4px; padding-right: 4px;" %>
<% end %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/index.js.erb
(function() {
  var $item = $('#myideas li.ideaid<%= @idea.id %> .item');
  var $link = $item.find('a.comment_link');
  $link.text( $link.text().replace(/\d+/, <%= @comments.length %>) );

  var $box =  $item.find('div.comments');
  $box.html( "<%= j render 'comment_box' %>" );
  $box.find('#comment_comment').focus();
}());