config/routes.rb
Redidea::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  match '/activities/my_index', :to => 'activities#my_index'
  resources :activities

  resources :advises, :only => [:index, :create, :update]

  devise_for :users do
    match "/users/sign_up" => redirect("/users/sign_in")
  end

  resources :comments
  root :to => "myspaces#show"
  resources :ideas
  match '/admin', :to => 'admins#admin'
  match '/invite', :to => 'admins#invite'
  match '/likes', :to => 'likes#create'
  resources :plans, :only => [:index, :create, :update]
  match '/static/an2012', :to => 'static#an2012'
  resources :messages
  match '/myspace', :to => 'myspaces#show'

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id         :integer(4)      not null, primary key
#  user_id    :integer(4)
#  name       :string(255)
#  describe   :text
#  created_at :datetime
#  updated_at :datetime
#

class Activity < ActiveRecord::Base
  has_many :ideas, :dependent => :destroy
  belongs_to :user
  attr_accessible :name, :describe, :created_at
  
  validates :name,     :presence => true, :length => { :within => 3..10 }
  validates :describe, :presence => true, :length => { :within => 3..65535 }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :navigate_bar
  before_filter :authorized_user, :only => :destroy

  # GET /activities
  # GET /activities.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    ideas_index
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @activity }
    end
  end

  def my_index
    @activities = Activity.all
    
    respond_to do |format|
      format.html { render :template => "activities/index.html.erb" }
    end
  end
  
  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :ok }
    end
  end
  
  private
  def authorized_user
    @activity = current_user.activities.find_by_id(params[:id])
    redirect_to root_path if @activity.nil?
  end
  
  def navigate_bar
    @my_activities = Activity.all
    @activities = Activity.all
  end
  
  def ideas_index
    @idea = Idea.new
    @ideas = Array.new
    @liked_ideas = Array.new
    @plans = current_user.plans

    @scope = params[:scope] || 'liked'
    @scopes = [:liked, :mine, :upload, :rule]

    if @scope == "mine" 
      @ideas = current_user.ideas
      @ideas.reverse!
    elsif @scope == "liked" 
      @liked_ideas = current_user.liking
      @ideas = Idea.all - @liked_ideas - current_user.ideas
      @liked_ideas.reverse!
    elsif @scope == "upload"
      @plan = Plan.find(:first, :conditions => "user_id = #{current_user.id}")
      if not @plan
        @plan = Plan.new
      end 
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_idea_form.html.erb
<%# encoding: utf-8 %>
<%= form_for(@idea, :remote => true) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :style => "width: 95%;" %>
  </div>
  <div class="field">
    <div class="idea_content">
      <div style="display: none;" node-type="num" class="num">
        请文明发言，还可以输入<span>400</span>字
      </div>
      <div class="title"><%= f.label :content %></div>
      <%= f.text_area :content, :style => "width: 95%;", :rows => 6 %>
    </div>
  </div>
  <button class='button' type='submit'>
    <%= image_tag "web-app-theme/icons/tick.png"%>发布
  </button>
  <p></p>
  <p></p>
<% end %>

app/views/activities/_my_ideas.html.erb
<%# encoding: utf-8 %>
<%# insert newly created idea into my list %>

<li class='ideaid<%= idea.id %>'>
<div class="left">
  <%= image_tag("/images/icons/#{idea.user_id % 67}.png") %>
	<div class="user_icon">
	<%if @scope!='mine' %>
		<span class="id<%= idea.user_id %>">
			<% num_of_ideas = User.find(:first, :conditions => "id = #{idea.user_id}").ideas.length %>
			<b>已发点子数:<%= num_of_ideas %></b>
			<b></b>
		</span>
	<%end%>
	</div>
</div>
<div class='item'>
  <b class="title"><%= idea.title %></b>
  <p><%= idea.content %></p>
  <div class='right small'>
    <% if @scope == 'mine' %>
      <% scores = [0,0,0,0] %>
      <% idea.likes.each{ |like| scores[like.score] += 1 } %>
      目前评价： 得分(<%= "#{scores[3]*2 + scores[2] - scores[0]}" %>)，关注(<%= "#{scores[3] + scores[2] + scores[0]}" %>)
    <%= link_to '删除点子', idea, :confirm => '无论评分高还是评分低，其实都是很有价值的点子。除非写错了，否则不需要删除。你确认删除？', :method => :delete, :class => 'small-button', :remote => true %>
    <%= link_to "评论(#{idea.comments.count})", comments_path(:idea_id => idea.id), { :remote => true, :class => "comment_link" } %>
  <% else %>
    <%= link_to '牛', likes_path(:idea_id => idea.id, :score => 3), :class => 'small-button', :remote => true %>
    <%= link_to '还不错', likes_path(:idea_id => idea.id, :score => 2), :class => 'small-button', :remote => true %>
    <%= link_to '没感觉', likes_path(:idea_id => idea.id, :score => 1), :class => 'small-button', :remote => true %>
    <%= link_to '不喜欢', likes_path(:idea_id => idea.id, :score => 0), :class => 'small-button', :remote => true %>
  <% end %>
</div>
<div class='small'>
  <%= time_ago_in_words(idea.created_at) %>前
</div>
<% if @scope=='mine' %>
<div class="id<%= idea.id %> comments"> 
</div>
<%end%>
      </div>
      </li>

app/views/activities/_myplan.html.erb
<%# encoding: utf-8 %>
<tr>
  <td class="title"><%= plan.title %></td>
  <td class="plan"><%= plan.plan.url.gsub(/.*\//, '') %></td>
</tr>

app/views/activities/_rule.html.erb
<%# encoding: utf-8 %>
<h2>欢迎参加红点子大奖赛</h2>
<p>很多同事都知道前一段时间收集新想法的头脑风暴活动，这个活动中我们想出了很多好的创新点子，为了鼓励大家想出更好的商业创意,公司现举办一个大奖赛，也拿出了很诱人的奖品，希望大家积极参与，提出更好的商业计划或者商业创意，赢取奖品。</p>

<h4>最佳商业计划奖：</h4>
<p><b>奖项设置:</b>一等奖一名,奖品为iPad一台; 二等奖二名,奖品为1TB USB3.0移动硬盘一个。</p>
<p><b>参赛办法:</b>请完成一份商业策划书，格式参考<%= link_to '商业策划书模板', "/plan_template.doc", :class => 'small-button' %>。在<%= link_to '"提交策划书"', "#{activity_path}?scope=upload" %>页面提交即可。（提示：模板中红色部分内容会作为评审重点，请格外关注）。</p>
<p><b>评奖办法：</b>本奖项由产品市场部特邀公司内部资深人士组成的评审委员会评审产生。 即刻行动起来吧，这轻轻的一笔或许能成就你非凡的未来！</p>

<h4>最佳商业创意奖：</h4>
<p><b>奖项设置:</b>一等奖一名,iPod touch4 一台；二等奖二名,奖品为1TB USB3.0移动硬盘一个</p>
<p><b>参赛办法:</b>在<%= link_to '"提交点子"', "#{activity_path}?scope=mine" %>页面提交你的创意点子，请尽量用简短的语言把你的想法描述清楚，以便争取更好的评价。（提示：用文字抓住读者的心是一门学问，通过简短的描述让表达更清晰是一种技巧，我想你懂的~~）。</p>
<p><b>评奖办法：</b>每个点子都会接受公司全体同事的评价，评价最好的点子将入围前10名，然后大家会对前10名再次进行10分制投票，得分最高的获得最终的“最佳商业创意奖”。现在就去支持你喜欢的<%= link_to '创意点子', "#{activity_path}?scope=liked" %>吧。</p>

<h4>截止日期</h4>
<p>两个奖项的截止时间均为2012年2月15日零点,过时将无法提交点子和策划书。</p>

<h4>评审时间</h4> 
<p> 2012年2月20日前完成评选</p>
<h4>注意事项</h4> 
<div class="content">
  <ul>
    <li>时值年底，很多同事手头的工作都进入了冲刺阶段，所以为了公平起见，请不要利用工作时间来完成本次参赛所需准备的作业。</li>
    <li>允许自行结合成课题组参加比赛，课题组的点子或者策划书请以组长个人身份在网站提交，提交时注明小组参赛即可</li>
  </ul>
</div>
<h2>祝你成功！</h2>
<p>2011年12月21日</p>

app/views/activities/_sidebar.html.erb
<%# encoding: utf-8 %>
<div class="block">
  <h3>活动</h3>
  <ul class="navigation">
    <li><%= link_to '全部活动', activities_path %></li>
    <li><%= link_to '我的活动', activities_my_index_path %></li>
    <li><%= link_to '创建活动', new_activity_path %></li>
  </ul>
</div>

<div class="block notice">
  <div class="content">
   <h5>红点子有奖竞赛</h5>
    <h4>最佳商业计划奖</h4>
      <p>一等奖奖品：<br \><p1>iPad</p1></p>
      <p>二等奖奖品：<br \><p1>1TB USB3.0移动硬盘</p1></p>
    <h4>最佳商业创意奖</h4>
      <p>一等奖奖品：<br \><p1>iPod touch4</p1></p>
      <p>二等奖奖品：<br \><p1>1TB USB3.0移动硬盘</p1></p>
  </div>
</div>

<!--<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>-->

app/views/activities/_upload.html.erb
<%# encoding: utf-8 %>
<div>
  <h2>从此处提交你的策划书<a href='/plan_template.doc'>(下载模版)</a></h2>
  <div>
    <strong>
      每个人允许提交多份策划书，但是上传同名的策划书会覆盖已有的。
    </strong>
  </div>

  <br>

  <%= form_for(@plan, :remote => true ) do |f| %>
    <div class="field">
      <%= f.label "策划书主题:" %>
      <%= f.text_field :title, :style => "width: 70%;" %>
    </div>
    <button class='button' type='submit'>
      <%= image_tag "web-app-theme/icons/tick.png"%>提交
    </button>
    <div class="field">
      <%= f.label "上传策划书: " %>
      <%= f.file_field :plan, :style => "width: 70%;" %>
    </div>
  <% end %>
</div>

<br>
<hr/>
<br>

<div id="plan_holder">
  <% if @plans.length > 0 %>
    <h2>已提交的策划书</h2>
    <table id="plans" class="myplan">
      <tbody>
        <tr>
          <th class="title">主题</th>
          <th class="plan">当前策划书</th>
        </tr>

        <%= render :partial => "ideas/myplan", :collection => @plans, :as => :plan %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/activities/create.js.erb
<% broadcast "/ideas/new" do  %>
{
  "user_email": "<%= current_user.email %>",
  "user_id": "<%= current_user.id %>",
  "action"   : "add"
}
<% end %>

<% if @idea.valid? %>
    $('#myideas').prepend( "<%= j render( :partial => 'my_ideas', :locals => { :idea => @idea }) %>" );
  $('#myideas > li:first').effect('highlight', {}, 3000);
  $('#new_idea')[0].reset();
  flashController.doSuccess('<p>创建成功</p>');
  commentsManager.bindHandlers();
<% else %>
    flashController.doFailure('<p>创建失败</p>');
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/fresh.js.erb
<%= @fresh_ideas.length %>,<%= @has_deletion %>,<%= @has_new_liking %>

app/views/activities/fresh.json.erb
{
  "fresh" : <%= @fresh_ideas %>,
  "total" : <%= @total %>, 
  "liked" : <%= @liked_ideas %>
}

app/views/activities/index.html.erb
<%# encoding: utf-8 %>

<div class="block">
<div class="content">
  <div class='inner'>
    <ul class='list'>
      <% @activities.each do |activity| %>
      <li>
        <div class='left'>
          <%= link_to activity.name, activity %>
        </div>
      </li>
      <div class='item'>
        <%= activity.describe %>
        <% if current_user == activity.user %>
          <%= link_to 'Edit', edit_activity_path(activity) %>
          <%= link_to 'Destroy', activity, confirm: 'Are you sure?', method: :delete %>
        <% else %>
          <%= activity.user.email %>
        <% end %>
      </div>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @activity.user == current_user %>
    <%= link_to 'Edit', edit_activity_path(@activity) %>
  <% else %>
    创建者：<%= @activity.user.email %>
  <% end %>
</p>

<h1><%= @activity.name %></h1>

<p>
  <%= @activity.describe.html_safe %>
</p>

<div class="block" id="block-text">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <% @scopes.each do |s| %>
      <li <%= "class='active first'" if s.to_s == @scope %> ><%= link_to t(s), "#{ideas_path}?scope=#{s}", :remote => true %></li>
      <% end %>
    </ul>
  </div>

  <div class="content">
    <% if @scope == 'rule' or @scope == 'upload' %>
    <%= render @scope %>
    <% else %>
    <%= render 'idea_box' %>
    <% end %>
  </div>
</div>

app/views/activities/show.js.erb
<%# encoding: utf-8 %>

(function() {
  var scope_pat = new RegExp("scope=(<%= j @scope %>)", 'g');

  <% if @scope == 'rule' or @scope == 'upload' %>
    var $active = $('.secondary-navigation .wat-cf li.active');
    if ($active.length) {
      var ret = scope_pat.exec( $active.find('a').attr('href') );
      if (ret && ret[1] === "<%= @scope %>") {
        return;
      } 
    }
    $('#main .block .content').html( "<%= j render @scope %>" );

  <% else %>
      $('#main .block .content').html( " <%= j render 'idea_box' %> " );
  <% end %>

  $('.secondary-navigation .wat-cf li').find('a').each( function(idx, el) {
    var ret = scope_pat.exec( $(el).attr('href') );
    if ( ret && ret[1] ) {
      $(el).parent().addClass('active first');
    } else {
      $(el).parent().removeClass('active first');
    }
  } );

})();